---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


## NOTICE on items in this file:
##   * If you use anything in the *._git_install_branch field that is not a TAG
##     make sure to leave an in-line comment as to "why".

## For the sake of anyone else editing this file:
##   * If you add services to this file please do so in alphabetical order.
##   * Every entry should be name spaced with the name of the client followed by an "_"
##   * All items with this file should be separated by `name_` note that the name of the
##     package should be one long name with no additional `_` separating it.


### Before this is shipped all of these services should have a tag set as the branch,
### or have a comment / reason attached to them as to why a tag can not work.


## Global Requirements
requirements_git_repo: https://git.openstack.org/openstack/requirements
requirements_git_install_branch: 0238d86161105168fb89f959476e667a2a97aa44 # HEAD of "stable/queens" as of 28.04.2018


## Aodh service
aodh_git_repo: https://git.openstack.org/openstack/aodh
aodh_git_install_branch: 149d3ad2193b4d17df801f82a0a6be62dba564db # HEAD of "stable/queens" as of 28.04.2018
aodh_git_project_group: aodh_all


## Barbican service
barbican_git_repo: https://git.openstack.org/openstack/barbican
barbican_git_install_branch: b10e100cb73eb26424d9d27782b8eadc3ad2e93c # HEAD of "stable/queens" as of 28.04.2018
barbican_git_project_group: barbican_all


## Ceilometer service
ceilometer_git_repo: https://git.openstack.org/openstack/ceilometer
ceilometer_git_install_branch: 420e621f40a70c7caa378f200c08520144c9a773 # HEAD of "stable/queens" as of 28.04.2018
ceilometer_git_project_group: ceilometer_all


## Cinder service
cinder_git_repo: https://git.openstack.org/openstack/cinder
cinder_git_install_branch: 0e77902d13e030881e16fb2ba0dc0b76ecba9665 # HEAD of "stable/queens" as of 28.04.2018
cinder_git_project_group: cinder_all


## Designate service
designate_git_repo: https://git.openstack.org/openstack/designate
designate_git_install_branch: cb60d7316c283667629355f33bf5602c4950101f # HEAD of "stable/queens" as of 28.04.2018
designate_git_project_group: designate_all


## Horizon Designate dashboard plugin
designate_dashboard_git_repo: https://git.openstack.org/openstack/designate-dashboard
designate_dashboard_git_install_branch: 6c8f5884ba3f36c178d38c26f308253200b8dd9a # HEAD of "stable/queens" as of 28.04.2018
designate_dashboard_git_project_group: horizon_all


## Dragonflow service
dragonflow_git_repo: https://git.openstack.org/openstack/dragonflow
dragonflow_git_install_branch: 2659025e9bb5d53626b71e31440f33788a0391de # HEAD of "master" as of 28.04.2018
dragonflow_git_project_group: neutron_all


## Glance service
glance_git_repo: https://git.openstack.org/openstack/glance
glance_git_install_branch: 01a76a09513a1e1c6fa55826be2e7e26ff5f4e82 # HEAD of "stable/queens" as of 28.04.2018
glance_git_project_group: glance_all


## Heat service
heat_git_repo: https://git.openstack.org/openstack/heat
heat_git_install_branch: 825731d81b6cba5d79cbab22a731965ff4f9c6a0 # HEAD of "stable/queens" as of 28.04.2018
heat_git_project_group: heat_all


## Horizon service
horizon_git_repo: https://git.openstack.org/openstack/horizon
horizon_git_install_branch: 85f1a633722c807ae3c4b96ffbf9ac3ae0a99d92 # HEAD of "stable/queens" as of 28.04.2018
horizon_git_project_group: horizon_all

## Horizon Ironic dashboard plugin
ironic_dashboard_git_repo: https://git.openstack.org/openstack/ironic-ui
ironic_dashboard_git_install_branch: 8ba23342cded6ff6bea4bb8633072c84acbf64d3 # HEAD of "stable/queens" as of 28.04.2018
ironic_dashboard_git_project_group: horizon_all

## Horizon Magnum dashboard plugin
magnum_dashboard_git_repo: https://git.openstack.org/openstack/magnum-ui
magnum_dashboard_git_install_branch: 53f5ab43e1697a1d2deeee3b4715cf56b010348b # HEAD of "stable/queens" as of 28.04.2018
magnum_dashboard_git_project_group: horizon_all

## Horizon LBaaS dashboard plugin
neutron_lbaas_dashboard_git_repo: https://git.openstack.org/openstack/neutron-lbaas-dashboard
neutron_lbaas_dashboard_git_install_branch: a2c502e406459b12a916f2e88ea026335fe61b5f # HEAD of "stable/queens" as of 28.04.2018
neutron_lbaas_dashboard_git_project_group: horizon_all

## Horizon FWaaS dashboard plugin
neutron_fwaas_dashboard_git_repo: https://git.openstack.org//openstack/neutron-fwaas-dashboard
neutron_fwaas_dashboard_git_install_branch: 80a23ecf0523d99595a1dd652554d63e8469bad1 # HEAD of "stable/queens" as of 28.04.2018
neutron_fwaas_dashboard_git_project_group: horizon_all

## Horizon Sahara dashboard plugin
sahara_dashboard_git_repo: https://git.openstack.org/openstack/sahara-dashboard
sahara_dashboard_git_install_branch: 707059ff4e372ae66b21b82050a9e16295176782 # HEAD of "stable/queens" as of 28.04.2018
sahara_dashboard_git_project_group: horizon_all

## Horizon Heat dashboard
heat_dashboard_git_repo: https://git.openstack.org/openstack/heat-dashboard
heat_dashboard_git_install_branch: 66d38448ed8d68c472ce2fdb373adeecc0f1f540 # HEAD of "stable/queens" as of 28.04.2018
heat_dashboard_git_project_group: horizon_all


## Keystone service
keystone_git_repo: https://git.openstack.org/openstack/keystone
keystone_git_install_branch: 7bd6454e4721d1ff4935ad36e30e5420ad10e70e # HEAD of "stable/queens" as of 28.04.2018
keystone_git_project_group: keystone_all


## Neutron service
neutron_git_repo: https://git.openstack.org/openstack/neutron
neutron_git_install_branch: f68e7822f46ec9577e5a866a67cc54b777240486 # HEAD of "stable/queens" as of 28.04.2018
neutron_git_project_group: neutron_all

neutron_lbaas_git_repo: https://git.openstack.org/openstack/neutron-lbaas
neutron_lbaas_git_install_branch: cdbf25c12edb993ea3c61edf71dae9529bbe04a9 # HEAD of "stable/queens" as of 28.04.2018
neutron_lbaas_git_project_group: neutron_all

neutron_vpnaas_git_repo: https://git.openstack.org/openstack/neutron-vpnaas
neutron_vpnaas_git_install_branch: 88478d5ca40108dc450aabb6d813bb6058d62cc7 # HEAD of "stable/queens" as of 28.04.2018
neutron_vpnaas_git_project_group: neutron_all

neutron_fwaas_git_repo: https://git.openstack.org/openstack/neutron-fwaas
neutron_fwaas_git_install_branch: 384366b3894611306b2b25203a7d63aba79c4f02 # HEAD of "stable/queens" as of 28.04.2018
neutron_fwaas_git_project_group: neutron_all

neutron_dynamic_routing_git_repo: https://git.openstack.org/openstack/neutron-dynamic-routing
neutron_dynamic_routing_git_install_branch: a29018ba87b18828c52326030413bc5e55f3668b # HEAD of "stable/queens" as of 28.04.2018
neutron_dynamic_routing_git_project_group: neutron_all

networking_calico_git_repo: https://git.openstack.org/openstack/networking-calico
networking_calico_git_install_branch: 7bfe655fba008e57971ee7ebde14bcd0c236ea53 # HEAD of "master" as of 28.04.2018
networking_calico_git_project_group: neutron_all

networking_odl_git_repo: https://git.openstack.org/openstack/networking-odl
networking_odl_git_install_branch: 8733cf68cbc827a4dd458e3328b5fd2c23a07bcf # HEAD of "stable/queens" as of 28.04.2018
networking_odl_git_project_group: neutron_all

networking_bgpvpn_git_repo: https://git.openstack.org/openstack/networking-bgpvpn
networking_bgpvpn_git_install_branch: a15c091d8a616c1fd1d3741f32c5d135b5db594f # HEAD of "stable/queens" as of 28.04.2018
networking_bgpvpn_git_project_group: neutron_all

networking_sfc_git_repo: https://git.openstack.org/openstack/networking-sfc
networking_sfc_git_install_branch: cbb68837a38428766ed4d22c5adfe3b2bc6c5f99 # HEAD of "stable/queens" as of 28.04.2018
networking_sfc_git_project_group: neutron_all


## Nova service
nova_git_repo: https://git.openstack.org/openstack/nova
nova_git_install_branch: a5aa8e2eb8d5a90780211ef67b8f2dcc76af64de # HEAD of "stable/queens" as of 28.04.2018
nova_git_project_group: nova_all


## PowerVM Virt Driver
nova_powervm_git_repo: https://git.openstack.org/openstack/nova-powervm
nova_powervm_git_install_branch: e62fae699d47feacd7372573948722cd0036996c # HEAD of "stable/queens" as of 28.04.2018
nova_powervm_git_project_group: nova_all


## LXD Virt Driver
nova_lxd_git_repo: https://git.openstack.org/openstack/nova-lxd
nova_lxd_git_install_branch: bdf27529a30c1a9c5046733dc2933b375d1ecc72 # HEAD of "stable/queens" as of 28.04.2018
nova_lxd_git_project_group: nova_all


## Sahara service
sahara_git_repo: https://git.openstack.org/openstack/sahara
sahara_git_install_branch: 016779b28ab25fa54154b1cccf7fd540f450fbe3 # HEAD of "stable/queens" as of 28.04.2018
sahara_git_project_group: sahara_all


## Swift service
swift_git_repo: https://git.openstack.org/openstack/swift
swift_git_install_branch: caeeb5412359d24b69013639a34272009cea5c63 # HEAD of "stable/queens" as of 28.04.2018
swift_git_project_group: swift_all


## Swift3 middleware
swift_swift3_git_repo: https://git.openstack.org/openstack/swift3
swift_swift3_git_install_branch: 520b8888343a96ef0253af8701b45f0bd5238264 # HEAD of "master" as of 28.04.2018
swift_swift3_git_project_group: swift_all


## Ironic service
ironic_git_repo: https://git.openstack.org/openstack/ironic
ironic_git_install_branch: 3538f2616ed9d2d61307b6b919881a9ccc1a0e6a # HEAD of "stable/queens" as of 28.04.2018
ironic_git_project_group: ironic_all


## Ironic inspector
ironic_inspector_git_repo: https://git.openstack.org/openstack/ironic-inspector
ironic_inspector_git_install_branch: 1eb1f6cc7cc5ae98a74304b40ffd8334d93210b6 #c312669bde68ffbbc22e115a4b0f4796bb613dd2 # HEAD of "master" as of 28.05.2018
ironic_inspector_git_project_group: ironic_inspector_all


## Magnum service
magnum_git_repo: https://git.openstack.org/openstack/magnum
magnum_git_install_branch: 9a01ab8a8aa2d79367bd0eb67188800b7ff3e927 # HEAD of "stable/queens" as of 28.04.2018
magnum_git_project_group: magnum_all


## Trove service
trove_git_repo: https://git.openstack.org/openstack/trove
trove_git_install_branch: 43d2b96f86a5365d69c885738ea1c3642f4e5aa1 # HEAD of "stable/queens" as of 28.04.2018
trove_git_project_group: trove_all

## Horizon Trove dashboard plugin
trove_dashboard_git_repo: https://git.openstack.org/openstack/trove-dashboard
trove_dashboard_git_install_branch: b3263223779d45377aa13906b8d4422d71e60c1b # HEAD of "stable/queens" as of 28.04.2018
trove_dashboard_git_project_group: horizon_all


## Octavia service
octavia_git_repo: https://git.openstack.org/openstack/octavia
octavia_git_install_branch: aa46758979f98eb9e2de1e8a70509916c6a88d99 # HEAD of "stable/queens" as of 28.04.2018
octavia_git_project_group: octavia_all

## Horizon Octavia dashboard plugin
octavia_dashboard_git_repo: https://git.openstack.org/openstack/octavia-dashboard
octavia_dashboard_git_install_branch: e68da46f599d1f8a76e7fd9ebec69548a5c49880 # HEAD of "stable/queens" as of 28.04.2018
octavia_dashboard_git_project_group: horizon_all


## Molteniron service
molteniron_git_repo: https://git.openstack.org/openstack/molteniron
molteniron_git_install_branch: 094276cda77d814d07ad885e7d63de8d1243750a # HEAD of "master" as of 28.04.2018
molteniron_git_project_group: molteniron_all


## Tacker service
tacker_git_repo: https://git.openstack.org/openstack/tacker
tacker_git_install_branch: 67404b21e17a1f77daea5fd891b11c5ec04d97ca # HEAD of "stable/queens" as of 28.04.2018
tacker_git_project_group: tacker_all
