---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


## NOTICE on items in this file:
##   * If you use anything in the *._git_install_branch field that is not a TAG
##     make sure to leave an in-line comment as to "why".

## For the sake of anyone else editing this file:
##   * If you add services to this file please do so in alphabetical order.
##   * Every entry should be name spaced with the name of the client followed by an "_"
##   * All items with this file should be separated by `name_` note that the name of the
##     package should be one long name with no additional `_` separating it.


### Before this is shipped all of these services should have a tag set as the branch,
### or have a comment / reason attached to them as to why a tag can not work.


## Global Requirements
requirements_git_repo: https://git.openstack.org/openstack/requirements
requirements_git_install_branch: b170ac9e34ad016ba19fcea57b37c7316ced2213 # HEAD of "stable/pike" as of 19.01.2018


## Aodh service
aodh_git_repo: https://git.openstack.org/openstack/aodh
aodh_git_install_branch: f0ec11eef92d39bd3f07e026a404e2e7aa7fa6bc # HEAD of "stable/pike" as of 19.01.2018
aodh_git_project_group: aodh_all


## Barbican service
barbican_git_repo: https://git.openstack.org/openstack/barbican
barbican_git_install_branch: 4aefe87d91715adf4a0bc3871956404ebe312fe3 # HEAD of "stable/pike" as of 19.01.2018
barbican_git_project_group: barbican_all


## Ceilometer service
ceilometer_git_repo: https://git.openstack.org/openstack/ceilometer
ceilometer_git_install_branch: 35a33b6daacfb9792382d4d5da4880737ab78fed # HEAD of "stable/pike" as of 19.01.2018
ceilometer_git_project_group: ceilometer_all


## Cinder service
cinder_git_repo: https://git.openstack.org/openstack/cinder
cinder_git_install_branch: 8f6bcc50f3a3f2ecc13dd0120e2c58804ea36cb3 # HEAD of "stable/pike" as of 19.01.2018
cinder_git_project_group: cinder_all


## Designate service
designate_git_repo: https://git.openstack.org/openstack/designate
designate_git_install_branch: 0c06a06fa409e1aebf97eb136d25b017598e2f88 # HEAD of "stable/pike" as of 19.01.2018
designate_git_project_group: designate_all


## Horizon Designate dashboard plugin
designate_dashboard_git_repo: https://git.openstack.org/openstack/designate-dashboard
designate_dashboard_git_install_branch: bc128a7c29a427933fc4ca94a7510ef8c97e5206 # HEAD of "stable/pike" as of 19.01.2018
designate_dashboard_git_project_group: horizon_all


## Dragonflow service
dragonflow_git_repo: https://git.openstack.org/openstack/dragonflow
dragonflow_git_install_branch: 84f1a26ff8e976b753593dc445e09a4c1a675a21 # Frozen HEAD of "master" as of 14.10.2017 (no stable/pike branch)
dragonflow_git_project_group: neutron_all


## Glance service
glance_git_repo: https://git.openstack.org/openstack/glance
glance_git_install_branch: 06af2eb5abe0332f7035a7d7c2fbfd19fbc4dae7 # HEAD of "stable/pike" as of 19.01.2018
glance_git_project_group: glance_all


## Heat service
heat_git_repo: https://git.openstack.org/openstack/heat
heat_git_install_branch: dc42b8f483c8947bdfc1b2c2db0b34bc9e0c9c68 # HEAD of "stable/pike" as of 19.01.2018
heat_git_project_group: heat_all


## Horizon service
horizon_git_repo: https://git.openstack.org/openstack/horizon
horizon_git_install_branch: 39d863ec239601ea6c57ef5273d6137d5930d80e # HEAD of "stable/pike" as of 19.01.2018
horizon_git_project_group: horizon_all

## Horizon Ironic dashboard plugin
ironic_dashboard_git_repo: https://git.openstack.org/openstack/ironic-ui
ironic_dashboard_git_install_branch: ca9f9f1e9c2baba5415bee2e7961221a3daa6da6 # HEAD of "stable/pike" as of 19.01.2018
ironic_dashboard_git_project_group: horizon_all

## Horizon Magnum dashboard plugin
magnum_dashboard_git_repo: https://git.openstack.org/openstack/magnum-ui
magnum_dashboard_git_install_branch: 0b9fc50aada1a3e214acaad1204b48c96a549e5f # HEAD of "stable/pike" as of 19.01.2018
magnum_dashboard_git_project_group: horizon_all

## Horizon LBaaS dashboard plugin
neutron_lbaas_dashboard_git_repo: https://git.openstack.org/openstack/neutron-lbaas-dashboard
neutron_lbaas_dashboard_git_install_branch: f51341588490baca3795b6f068347cd2260d2e3b # HEAD of "stable/pike" as of 19.01.2018
neutron_lbaas_dashboard_git_project_group: horizon_all

## Horizon Sahara dashboard plugin
sahara_dashboard_git_repo: https://git.openstack.org/openstack/sahara-dashboard
sahara_dashboard_git_install_branch: 5b28b7bca87d3fff130fb262b858068efb740d1a # HEAD of "stable/pike" as of 19.01.2018
sahara_dashboard_git_project_group: horizon_all


## Keystone service
keystone_git_repo: https://git.openstack.org/openstack/keystone
keystone_git_install_branch: e851e0046fcdfd80787d8efdccdf0362fdd7b5db # HEAD of "stable/pike" as of 19.01.2018
keystone_git_project_group: keystone_all


## Neutron service
neutron_git_repo: https://git.openstack.org/openstack/neutron
neutron_git_install_branch: 8a943e4dbe4e46e1175fd8fc2eee133af508c068 # HEAD of "stable/pike" as of 19.01.2018
neutron_git_project_group: neutron_all

neutron_lbaas_git_repo: https://git.openstack.org/openstack/neutron-lbaas
neutron_lbaas_git_install_branch: 49448db1a69d53ad0d137216b1805690a7daef45 # HEAD of "stable/pike" as of 19.01.2018
neutron_lbaas_git_project_group: neutron_all

neutron_vpnaas_git_repo: https://git.openstack.org/openstack/neutron-vpnaas
neutron_vpnaas_git_install_branch: 60e4e7113b5fbbf28e97ebce2f40b7f1675200e6 # HEAD of "stable/pike" as of 19.01.2018
neutron_vpnaas_git_project_group: neutron_all

neutron_fwaas_git_repo: https://git.openstack.org/openstack/neutron-fwaas
neutron_fwaas_git_install_branch: ea4e95913d843d72c8a3079203171813ba69895d # HEAD of "stable/pike" as of 19.01.2018
neutron_fwaas_git_project_group: neutron_all

neutron_dynamic_routing_git_repo: https://git.openstack.org/openstack/neutron-dynamic-routing
neutron_dynamic_routing_git_install_branch: 9098d4447581117e857d2f86fb4a0508b5ffbb6a # HEAD of "stable/pike" as of 19.01.2018
neutron_dynamic_routing_git_project_group: neutron_all

networking_calico_git_repo: https://git.openstack.org/openstack/networking-calico
networking_calico_git_install_branch: 8b55fb6c7645011020e78c592721c085c92b2c51 # HEAD of "master" as of 19.01.2018
networking_calico_git_project_group: neutron_all

## Nova service
nova_git_repo: https://git.openstack.org/openstack/nova
nova_git_install_branch: b535f0808526c8eba37f15e83cede536e4e06029 # HEAD of "stable/pike" as of 19.01.2018
nova_git_project_group: nova_all


## PowerVM Virt Driver
nova_powervm_git_repo: https://git.openstack.org/openstack/nova-powervm
nova_powervm_git_install_branch: e0b516ca36fa5dfd38ae6f7ea97afd9a52f313ed # HEAD of "stable/pike" as of 19.01.2018
nova_powervm_git_project_group: nova_all


## LXD Virt Driver
nova_lxd_git_repo: https://git.openstack.org/openstack/nova-lxd
nova_lxd_git_install_branch: 9747c274138d9ef40512d5015e9e581f6bbec5d9 # HEAD of "stable/pike" as of 19.01.2018
nova_lxd_git_project_group: nova_all


## Sahara service
sahara_git_repo: https://git.openstack.org/openstack/sahara
sahara_git_install_branch: a39c690aeca04dcde56384448ce577fd50eb8bf1 # HEAD of "stable/pike" as of 19.01.2018
sahara_git_project_group: sahara_all


## Swift service
swift_git_repo: https://git.openstack.org/openstack/swift
swift_git_install_branch: 0ff2d5e3b85a42914a89eac64ed9a87172334a2c # HEAD of "stable/pike" as of 19.01.2018
swift_git_project_group: swift_all


## Swift3 middleware
swift_swift3_git_repo: https://git.openstack.org/openstack/swift3
swift_swift3_git_install_branch: 1c117c96dda8113c3398c16e68b61efef397de74 # HEAD of "master" as of 19.01.2018
swift_swift3_git_project_group: swift_all


## Ironic service
ironic_git_repo: https://git.openstack.org/openstack/ironic
ironic_git_install_branch: a26082ac195cb3d4a9f5f6f7638d1357c58d3e03 # HEAD of "stable/pike" as of 19.01.2018
ironic_git_project_group: ironic_all

## Ironic inspector
ironic_inspector_git_repo: https://git.openstack.org/openstack/ironic-inspector
ironic_inspector_git_install_branch: 3b9e4c065655550ff6c5076d1f7c9129bdf413ee #35828784d5124dfc66842a790282f9f7d03251fe 
ironic_inspector_git_project_group: ironic_inspector_all

## Magnum service
magnum_git_repo: https://git.openstack.org/openstack/magnum
magnum_git_install_branch: 1594d552c4027e5ede501ba83e06f89a0c8e3849 # HEAD of "stable/pike" as of 19.01.2018
magnum_git_project_group: magnum_all

## Trove service
trove_git_repo: https://git.openstack.org/openstack/trove
trove_git_install_branch: 2a39699f8612a8f82dfce68949b714d19a102499 # HEAD of "stable/pike" as of 19.01.2018
trove_git_project_group: trove_all

## Horizon Trove dashboard plugin
trove_dashboard_git_repo: https://git.openstack.org/openstack/trove-dashboard
trove_dashboard_git_install_branch: bffd0776d139f38f96ce8ded07ccde4b5a41bc7a # HEAD of "stable/pike" as of 19.01.2018
trove_dashboard_git_project_group: horizon_all

## Octavia service
octavia_git_repo: https://git.openstack.org/openstack/octavia
octavia_git_install_branch: d9e24e83bbf7d12f8bec16072b28c6ca655690ac # HEAD of "stable/pike" as of 19.01.2018
octavia_git_project_group: octavia_all

## Molteniron service
molteniron_git_repo: https://git.openstack.org/openstack/molteniron
molteniron_git_install_branch: 094276cda77d814d07ad885e7d63de8d1243750a # HEAD of "master" as of 19.01.2018
molteniron_git_project_group: molteniron_all
