---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


## NOTICE on items in this file:
##   * If you use anything in the *._git_install_branch field that is not a TAG
##     make sure to leave an in-line comment as to "why".

## For the sake of anyone else editing this file:
##   * If you add services to this file please do so in alphabetical order.
##   * Every entry should be name spaced with the name of the client followed by an "_"
##   * All items with this file should be separated by `name_` note that the name of the
##     package should be one long name with no additional `_` separating it.


### Before this is shipped all of these services should have a tag set as the branch,
### or have a comment / reason attached to them as to why a tag can not work.


## Global Requirements
requirements_git_repo: https://opendev.org/openstack/requirements
requirements_git_install_branch: d4f1977da2dc3c1e8c22bc835fa597ef09a7b8bc # HEAD as of 20.10.2019
requirements_git_track_branch: stable/stein


## Aodh service
aodh_git_repo: https://opendev.org/openstack/aodh
aodh_git_install_branch: 43e3b39a649897344ca863e6c8b4e85d5b32d4b7  # HEAD as of 20.10.2019
aodh_git_project_group: aodh_all
aodh_git_track_branch: stable/stein


## Barbican service
barbican_git_repo: https://opendev.org/openstack/barbican
barbican_git_install_branch: 7a3396dc2d1146e83a5851b74f72af4d280c33b9  # HEAD as of 20.10.2019
barbican_git_project_group: barbican_all
barbican_git_track_branch: stable/stein


## Ceilometer service
ceilometer_git_repo: https://opendev.org/openstack/ceilometer
ceilometer_git_install_branch: 824be970df31b398a9ce71c4b56185150d4ebbb8  # HEAD as of 20.10.2019
ceilometer_git_project_group: all
ceilometer_git_track_branch: stable/stein


## Cinder service
cinder_git_repo: https://opendev.org/openstack/cinder
cinder_git_install_branch: 81cce7db7ba1c8a3056b4bc8761b93d4a4733067  # HEAD as of 20.10.2019
cinder_git_project_group: cinder_all
cinder_git_track_branch: stable/stein


## Designate service
designate_git_repo: https://opendev.org/openstack/designate
designate_git_install_branch: 3382867b38cf3f72ec494794bceaa5523b43d9c4  # HEAD as of 20.10.2019
designate_git_project_group: designate_all
designate_git_track_branch: stable/stein


## Horizon Designate dashboard plugin
designate_dashboard_git_repo: https://opendev.org/openstack/designate-dashboard
designate_dashboard_git_install_branch: b8dc251792ffdc84d06091242880166d48e6c873  # HEAD as of 20.10.2019
designate_dashboard_git_project_group: horizon_all
designate_dashboard_git_track_branch: stable/stein


## Glance service
glance_git_repo: https://opendev.org/openstack/glance
glance_git_install_branch: 0e8f37c35a9ef89d12d8cfcc507ed8c724badd98  # HEAD as of 20.10.2019
glance_git_project_group: glance_all
glance_git_track_branch: stable/stein


## Heat service
heat_git_repo: https://opendev.org/openstack/heat
heat_git_install_branch: 425260920790b1d39668b7bbe00812d61e6fa0e9  # HEAD as of 20.10.2019
heat_git_package_name: openstack-heat
heat_git_project_group: heat_all
heat_git_track_branch: stable/stein

## Horizon Heat dashboard plugin
heat_dashboard_git_repo: https://opendev.org/openstack/heat-dashboard
heat_dashboard_git_install_branch: c8d8cab3557f76f5363822f1bb2cbe1ec32858d3  # HEAD as of 20.10.2019
heat_dashboard_git_project_group: horizon_all
heat_dashboard_git_track_branch: stable/stein

## Horizon service
horizon_git_repo: https://opendev.org/openstack/horizon
horizon_git_install_branch: 77b0242fa2ce64ab77ea7e4ee7a8530de044967e  # HEAD as of 20.10.2019
horizon_git_project_group: horizon_all
horizon_git_track_branch: stable/stein

## Horizon Ironic dashboard plugin
ironic_dashboard_git_repo: https://opendev.org/openstack/ironic-ui
ironic_dashboard_git_install_branch: 859560fe8722edbd61a79d3137814295fad43b61  # HEAD as of 20.10.2019
ironic_dashboard_git_project_group: horizon_all
ironic_dashboard_git_track_branch: stable/stein

## Horizon Magnum dashboard plugin
magnum_dashboard_git_repo: https://opendev.org/openstack/magnum-ui
magnum_dashboard_git_install_branch: 2e494fb673fc79dbbc94ff67644eaf8f42efce6c  # HEAD as of 20.10.2019
magnum_dashboard_git_project_group: horizon_all
magnum_dashboard_git_track_branch: stable/stein

## Horizon Masakari dashboard plugin
masakari_dashboard_git_repo: https://opendev.org/openstack/masakari-dashboard
masakari_dashboard_git_install_branch: 2ddff1358068b384e51cd0a32e313da963096740  # HEAD as of 20.10.2019
masakari_dashboard_git_project_group: horizon_all
masakari_dashboard_git_track_branch: stable/stein

## Horizon LBaaS dashboard plugin
neutron_lbaas_dashboard_git_repo: https://opendev.org/openstack/neutron-lbaas-dashboard
neutron_lbaas_dashboard_git_install_branch: 87d0c15b10f9087de5f80d5565f41c884f91db59  # HEAD as of 20.10.2019
neutron_lbaas_dashboard_git_project_group: horizon_all
neutron_lbaas_dashboard_git_track_branch: stable/stein

## Horizon FWaaS dashboard plugin
neutron_fwaas_dashboard_git_repo: https://opendev.org/openstack/neutron-fwaas-dashboard
neutron_fwaas_dashboard_git_install_branch: 585ea863b6a3660ea4564f030b4e979417451bcf  # HEAD as of 20.10.2019
neutron_fwaas_dashboard_git_project_group: horizon_all
neutron_fwaas_dashboard_git_track_branch: stable/stein

## Horizon Sahara dashboard plugin
sahara_dashboard_git_repo: https://opendev.org/openstack/sahara-dashboard
sahara_dashboard_git_install_branch: 5f297e007943c9345792fe243a9f4f0c109f980a # HEAD as of 20.10.2019
sahara_dashboard_git_project_group: horizon_all
sahara_dashboard_git_track_branch: stable/stein


## Keystone service
keystone_git_repo: https://opendev.org/openstack/keystone
keystone_git_install_branch: 1efa20fc36b24ae2f56ec4187115bf5e75bee32d  # HEAD as of 20.10.2019
keystone_git_project_group: keystone_all
keystone_git_track_branch: stable/stein


## Manila service
manila_git_repo: https://opendev.org/openstack/manila
manila_git_install_branch: fa91061bb623dcf4f9fa069b4a8ec120aa07c504  # HEAD as of 20.10.2019
manila_git_project_group: manila_all
manila_git_track_branch: stable/stein


## Neutron service
neutron_git_repo: https://opendev.org/openstack/neutron
neutron_git_install_branch: 89b265898f3b88c6e2d1e07430c39b0e76a7e05c  # HEAD as of 20.10.2019
neutron_git_project_group: neutron_all
neutron_git_track_branch: stable/stein

neutron_lbaas_git_repo: https://opendev.org/openstack/neutron-lbaas
neutron_lbaas_git_install_branch: 52adf0ac369839dda0ae90d6735bab5e6e62646b  # HEAD as of 20.10.2019
neutron_lbaas_git_project_group: neutron_all
neutron_lbaas_git_track_branch: stable/stein

neutron_vpnaas_git_repo: https://opendev.org/openstack/neutron-vpnaas
neutron_vpnaas_git_install_branch: 659a8cd7fe2581b7e7d7b1e60b18a4630c9d7058  # HEAD as of 20.10.2019
neutron_vpnaas_git_project_group: neutron_all
neutron_vpnaas_git_track_branch: stable/stein

neutron_fwaas_git_repo: https://opendev.org/openstack/neutron-fwaas
neutron_fwaas_git_install_branch: 2febe3fe994a3de779218b4733ffa6bc08f072b8  # HEAD as of 20.10.2019
neutron_fwaas_git_project_group: neutron_all
neutron_fwaas_git_track_branch: stable/stein

neutron_dynamic_routing_git_repo: https://opendev.org/openstack/neutron-dynamic-routing
neutron_dynamic_routing_git_install_branch: f313f0e9c030849d62e6bc4c9511efe9623ab06f  # HEAD as of 20.10.2019
neutron_dynamic_routing_git_project_group: neutron_all
neutron_dynamic_routing_git_track_branch: stable/stein

# Networking calico follows master
networking_calico_git_repo: https://opendev.org/openstack/networking-calico
networking_calico_git_install_branch: 79bdf4995d102833d23479180350216fc59e4b94  # HEAD as of 20.10.2019
networking_calico_git_project_group: neutron_all
networking_calico_git_track_branch: master

networking_odl_git_repo: https://opendev.org/openstack/networking-odl
networking_odl_git_install_branch: 5b062f03e795809760b706d7700b53c8ef038a7f  # HEAD as of 20.10.2019
networking_odl_git_project_group: neutron_all
networking_odl_git_track_branch: stable/stein

networking_ovn_git_repo: https://opendev.org/openstack/networking-ovn
networking_ovn_git_install_branch: 704a4ccb82b06634ffa51aa2d59fb47ee4a88497  # HEAD as of 20.10.2019
networking_ovn_git_project_group: neutron_all
networking_ovn_git_track_branch: stable/stein

# BGPVPN is frozen until further notice due to
# https://github.com/openstack/networking-bgpvpn/commit/e9a0ea199b47f76f69545e04bdb4db44869c388b#diff-b4ef698db8ca845e5845c4618278f29a
networking_bgpvpn_git_repo: https://opendev.org/openstack/networking-bgpvpn
networking_bgpvpn_git_install_branch: 3b93ddacd390d92fb144e5660324d4da064ad9a4 # FROZEN HEAD of "stable/stein" as of 31.03.2018
networking_bgpvpn_git_project_group: neutron_all
networking_bgpvpn_git_track_branch: None

networking_sfc_git_repo: https://opendev.org/openstack/networking-sfc
networking_sfc_git_install_branch: 8bee6b4896d7a5428b3e4053c7f3d0786412603f  # HEAD as of 20.10.2019
networking_sfc_git_project_group: neutron_all
networking_sfc_git_track_branch: stable/stein


## Nova service
nova_git_repo: https://opendev.org/openstack/nova
nova_git_install_branch: a06922d546a26c9e6550a93cbe0718cf841b6b9f  # HEAD as of 20.10.2019
nova_git_project_group: nova_all
nova_git_track_branch: stable/stein


## PowerVM Virt Driver
nova_powervm_git_repo: https://opendev.org/openstack/nova-powervm
nova_powervm_git_install_branch: 6806d3d6f673fbe75f7df7fc40fe9fc04088e34f  # HEAD as of 20.10.2019
nova_powervm_git_project_group: nova_all
nova_powervm_git_track_branch: stable/stein


## LXD Virt Driver
nova_lxd_git_repo: https://opendev.org/x/nova-lxd
nova_lxd_git_install_branch: edae0af78020f0fa63c63fa3573f1d93ac93c0b9  # HEAD as of 20.10.2019
nova_lxd_git_project_group: nova_all
nova_lxd_git_track_branch: stable/stein


## Sahara service
sahara_git_repo: https://opendev.org/openstack/sahara
sahara_git_install_branch: 1fa76ce666539a2d8381cad5286993e27322b56a # HEAD as of 20.10.2019
sahara_git_project_group: sahara_all
sahara_git_track_branch: stable/stein


## Swift service
swift_git_repo: https://opendev.org/openstack/swift
swift_git_install_branch: a911bf25798aeec7ae4582a277b094f8ca136cc6 # HEAD as of 20.10.2019
swift_git_project_group: swift_all
swift_git_track_branch: stable/stein


## Ironic service
ironic_git_repo: https://opendev.org/openstack/ironic
ironic_git_install_branch: 39196ca9ef042cd056afed08deaa620cc83f58a8  # HEAD as of 20.10.2019
ironic_git_project_group: ironic_all
ironic_git_track_branch: stable/stein


## Ironic inspector
ironic_inspector_git_repo: https://git.openstack.org/openstack/ironic-inspector
ironic_inspector_git_install_branch: c7a4ec8a3b332a320444c664d0e5c45ada048a64
ironic_inspector_git_project_group: ironic_inspector_all
ironic_inspector_git_track_branch: stable/stein


## Magnum service
magnum_git_repo: https://opendev.org/openstack/magnum
magnum_git_install_branch: 9493f4db27668a4b1fa0a9889ef9d3a932cd79aa  # HEAD as of 20.10.2019
magnum_git_project_group: magnum_all
magnum_git_track_branch: stable/stein

## Masakari service
masakari_git_repo: https://opendev.org/openstack/masakari
masakari_git_install_branch: df08881742a18c5100f59d06889120b277b98911  # HEAD as of 20.10.2019
masakari_git_project_group: masakari_api
masakari_git_track_branch: stable/stein

## Masakari monitors services
masakari_monitors_git_repo: https://opendev.org/openstack/masakari-monitors
masakari_monitors_git_install_branch: 77132bbdbda459177e815f6412924d70cbc5d87f  # HEAD as of 20.10.2019
masakari_monitors_git_project_group: masakari_monitor
masakari_monitors_git_track_branch: stable/stein

## Mistral service
mistral_git_repo: https://opendev.org/openstack/mistral
mistral_git_install_branch: 19ddb052b3f7d78dd22c354682cb9090ce6d2001  # HEAD as of 20.10.2019
mistral_git_project_group: mistral_all
mistral_git_track_branch: stable/stein

## Trove service
trove_git_repo: https://opendev.org/openstack/trove
trove_git_install_branch: 67566d07b5308ab7ad1cc91729162b65d8da8638 # HEAD as of 20.10.2019
trove_git_project_group: trove_all
trove_git_track_branch: stable/stein

## Horizon Trove dashboard plugin
trove_dashboard_git_repo: https://opendev.org/openstack/trove-dashboard
trove_dashboard_git_install_branch: ebb414093c2ccd0ef1a650f5110cac5d29934462 # HEAD as of 20.10.2019
trove_dashboard_git_project_group: horizon_all
trove_dashboard_git_track_branch: stable/stein


## Octavia service
octavia_git_repo: https://opendev.org/openstack/octavia
octavia_git_install_branch: e51752e43305cc2d7446aa4af89378878708e73e  # HEAD as of 20.10.2019
octavia_git_project_group: octavia_all
octavia_git_track_branch: stable/stein


## Panko service
panko_git_repo: https://opendev.org/openstack/panko
panko_git_install_branch: cc4fbd4704f89e570e36b7a5f652fadf68f3eb6f  # HEAD as of 20.10.2019
panko_git_project_group: panko_all
panko_git_track_branch: stable/stein


## Tacker service
tacker_git_repo: https://opendev.org/openstack/tacker
tacker_git_install_branch: aee46c86bbe87cbb8b6ebb3bd9b765aafd13df53 # HEAD as of 20.10.2019
tacker_git_project_group: tacker_all
tacker_git_track_branch: stable/stein


## Congress service
congress_git_repo: https://opendev.org/openstack/congress
congress_git_install_branch: b565c87d0224abb76d3710a4238df433f75ffbf3  # HEAD as of 20.10.2019
congress_git_package_name: openstack-congress
congress_git_project_group: congress_all
congress_git_track_branch: stable/stein

## Horizon Octavia dashboard plugin
octavia_dashboard_git_repo: https://opendev.org/openstack/octavia-dashboard
octavia_dashboard_git_install_branch: 13c01348f5275c7afe4130dc0a3b072d89cae4af  # HEAD as of 20.10.2019
octavia_dashboard_git_project_group: horizon_all
octavia_dashboard_git_track_branch: stable/stein


## Blazar service
blazar_git_repo: https://opendev.org/openstack/blazar
blazar_git_install_branch: 536ea887b96424d6a81e33b9fea576cdb2173d1d  # HEAD as of 20.10.2019
blazar_git_project_group: blazar_all
blazar_git_track_branch: stable/stein

## Blazar Nova Service
blazar_nova_git_repo: https://opendev.org/openstack/blazar-nova
blazar_nova_git_install_branch: 334965654ba3ce5a62a25ede5250c2e2c05c064d  # HEAD as of 20.10.2019
blazar_nova_git_project_group: blazar_all
blazar_nova_git_track_branch: stable/stein
